### ISSUE TITLE
Flashing unsigned BIOS

### ISSUE THREAD

**Issue by haarp** [Cr4sh/ThinkPwn#2]
Hey,

nice find!

> Running of arbitrary System Management Mode code allows attacker to disable flash write protection

Could this be used to flash unsigned (i.e. modded) BIOS versions? This has been a major challenge in newer Thinkpads (**30+ Generation). Being able to flash without a hardware programmer could be an actual valid use case of this vulnerability!

**Comment by c0d3z3r0** [comment]
Even if it was possible to write an unsigned UEFI/BIOS it won't boot since Intel BootGuard prevents it

**Comment by haarp** [comment]
BootGuard is not present/activated on all Thinkpad hardware. At least the **30 generation will boot unsigned firmwares if it is flashed externally.

**Comment by trilader** [comment]
That also applies to (at least some of) the *20 Thinkpads. Source: I have an x220 running Coreboot.

**Comment by Cr4sh** [comment]
Project is issues is not a proper place for such discussions
